### ISSUE TITLE
Handlebars

### ISSUE THREAD

**Issue by saukchung** [SDMNNY/get-pawned-chess-game-#16]
- [x] welcome page
- [x] Login
- [ ] User page - lists all the current games/basic user info("logged in")
- [ ] Challenge page - lists all the users(Name, matchHistory, "Challenge"/"Accept Challenge" button)
- [x] (individual)Game - shows the board, shows the game status
- [x] logout

**Comment by TutorJustus** [comment]
@saukchung get in touch fulldevtutor@gmail.com. will sort this out. TIA.
